services:
  strm-generator:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64 # x86_64 架构
        - linux/arm64 # ARM 架构
    ports:
      - "3000:3000" # 后端 API 端口
      - "5255:80" # 前端页面端口
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/data/database
      - ALIST_HOST=http://192.168.92.120:5244
      - ALIST_TOKEN=alist-d8bc1b41-78a0-4707-b59e-2fcf83edc9f8b7cz4OtGfTxpCRrpDfbMJSZ3mQcJLQysNU8W9qeXOstIBDslUPTxd8v3w7bLqISX
      - LOG_BASE_DIR=/data/logs
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
    restart: unless-stopped

volumes:
  data:
