services:
  alist2strm:
    image: mccray/alist2strm:latest
    container_name: alist2strm
    restart: unless-stopped
    ports:
      - "3456:80"   # 前端访问端口
      - "4567:3000" # 后端API端口
    volumes:
      - ./data:/app/data
    environment:
      - 'PUID=1000'
      - 'PGID=100'
      - 'UMASK=022'
      - 'TZ=Asia/Shanghai'
      # 服务器配置
      - PORT=3210
      # 日志配置
      - LOG_BASE_DIR=/app/data/logs
      - LOG_LEVEL=info
      - LOG_APP_NAME=alist2strm
      - LOG_MAX_DAYS=30
      - LOG_MAX_FILE_SIZE=10
      # 数据库配置
      - DB_BASE_DIR=/app/data/db
      - DB_NAME=database.sqlite
    networks:
      - alist2strm-network

networks:
  alist2strm-network:
    name: alist2strm-network
    driver: bridge